### ISSUE TITLE
Add next due date to admin

### ISSUE THREAD

**Issue by FuchieSteph** [olivierdalang/django-toosimple-q#6]
Hi,

First thank you, the module works really well :) . I was looking for an alternative to background_tasks & it's definitely a good one.

I was thinking that it could maybe be interesting to add to the schedule admin table the date of the next schedule ? 

It's quite easy to add it with croniter : 

```python
@admin.display(ordering="next_run__due")
def next_run_due_(self, obj): 
       return croniter(obj.schedule.cron, timezone.now()).get_next(datetime)
```

**Comment by olivierdalang** [comment]
Thanks !

Liked the idea, done in #12. Don't hesitate to test and give feedback
